/**
 * Server-side card data (game-logic fields only).
 * No imagePath, no description tokens — those are client-only.
 * All 70 cards: id, name, family, cost, effectTypes (which effect types exist on the card).
 */

/** @type {Record<number, { id: number, name: string, family: string, cost: number, effectTypes: string[] }>} */
export const CardData = {
	// ── Fire ────────────────────────────────────────────────────────────────
	1: { id: 1, name: "Agni", family: "fire", cost: 4 },
	2: { id: 2, name: "Asmodeus", family: "fire", cost: 4 },
	3: { id: 3, name: "Balog", family: "fire", cost: 4 },
	4: { id: 4, name: "Burning Skull", family: "fire", cost: 3 },
	5: { id: 5, name: "Firefox", family: "fire", cost: 1 },
	6: { id: 6, name: "Hestia", family: "fire", cost: 0 },
	7: { id: 7, name: "Horned Salamander", family: "fire", cost: 2 },
	8: { id: 8, name: "Ifrit", family: "fire", cost: 2 },
	9: { id: 9, name: "Imp", family: "fire", cost: 0 },
	10: { id: 10, name: "Incubus", family: "fire", cost: 2 },
	11: { id: 11, name: "Lava Giant", family: "fire", cost: 3 },
	12: { id: 12, name: "Phoenix", family: "fire", cost: 3 },
	13: { id: 13, name: "Salamander", family: "fire", cost: 1 },
	14: { id: 14, name: "Succubus", family: "fire", cost: 0 },
	15: { id: 15, name: "Surtr", family: "fire", cost: 4 },
	// ── Water ───────────────────────────────────────────────────────────────
	16: { id: 16, name: "Charybdis", family: "water", cost: 5 },
	17: { id: 17, name: "Hae-tae", family: "water", cost: 3 },
	18: { id: 18, name: "Hydra", family: "water", cost: 4 },
	19: { id: 19, name: "Kappa", family: "water", cost: 1 },
	20: { id: 20, name: "Leviathan", family: "water", cost: 4 },
	21: { id: 21, name: "Nessie", family: "water", cost: 2 },
	22: { id: 22, name: "Poseidon", family: "water", cost: 7 },
	23: { id: 23, name: "Sea Spirit", family: "water", cost: 1 },
	24: { id: 24, name: "Snail Maiden", family: "water", cost: 3 },
	25: { id: 25, name: "Triton", family: "water", cost: 4 },
	26: { id: 26, name: "Undine", family: "water", cost: 1 },
	27: { id: 27, name: "Undine Queen", family: "water", cost: 3 },
	28: { id: 28, name: "Water Giant", family: "water", cost: 4 },
	29: { id: 29, name: "Yuki Onna", family: "water", cost: 0 },
	30: { id: 30, name: "Yuki Onna Exalted", family: "water", cost: 3 },
	// ── Earth ───────────────────────────────────────────────────────────────
	31: { id: 31, name: "Basilisk", family: "earth", cost: 3 },
	32: { id: 32, name: "Behemoth", family: "earth", cost: 9 },
	33: { id: 33, name: "Cerberus", family: "earth", cost: 5 },
	34: { id: 34, name: "Forest Spirit", family: "earth", cost: 2 },
	35: { id: 35, name: "Gargoyle", family: "earth", cost: 2 },
	36: { id: 36, name: "Goblin", family: "earth", cost: 1 },
	37: { id: 37, name: "Goblin Soldier", family: "earth", cost: 4 },
	38: { id: 38, name: "Medusa", family: "earth", cost: 4 },
	39: { id: 39, name: "Mimic", family: "earth", cost: 6 },
	40: { id: 40, name: "Mud Slime", family: "earth", cost: 6 },
	41: { id: 41, name: "Rock Golem", family: "earth", cost: 6 },
	42: { id: 42, name: "Sand Giant", family: "earth", cost: 10 },
	43: { id: 43, name: "Stone Golem", family: "earth", cost: 6 },
	44: { id: 44, name: "Troll", family: "earth", cost: 3 },
	45: { id: 45, name: "Young Forest Spirit", family: "earth", cost: 0 },
	// ── Wind ────────────────────────────────────────────────────────────────
	46: { id: 46, name: "Boreas", family: "wind", cost: 4 },
	47: { id: 47, name: "Dandelion Spirit", family: "wind", cost: 3 },
	48: { id: 48, name: "Freyja", family: "wind", cost: 7 },
	49: { id: 49, name: "Genie", family: "wind", cost: 4 },
	50: { id: 50, name: "Genie Exalted", family: "wind", cost: 5 },
	51: { id: 51, name: "Gi-rin", family: "wind", cost: 10 },
	52: { id: 52, name: "Griffon", family: "wind", cost: 7 },
	53: { id: 53, name: "Harpy", family: "wind", cost: 3 },
	54: { id: 54, name: "Hippogriff", family: "wind", cost: 4 },
	55: { id: 55, name: "Odin", family: "wind", cost: 6 },
	56: { id: 56, name: "Pegasus", family: "wind", cost: 3 },
	57: { id: 57, name: "Rudra", family: "wind", cost: 8 },
	58: { id: 58, name: "Sylph", family: "wind", cost: 4 },
	59: { id: 59, name: "Tengu", family: "wind", cost: 3 },
	60: { id: 60, name: "Valkyrie", family: "wind", cost: 5 },
	// ── Dragon ──────────────────────────────────────────────────────────────
	61: { id: 61, name: "Aeris", family: "dragon", cost: 9 },
	62: { id: 62, name: "Boulder", family: "dragon", cost: 8 },
	63: { id: 63, name: "Dragon Egg", family: "dragon", cost: 3 },
	64: { id: 64, name: "Ember", family: "dragon", cost: 7 },
	65: { id: 65, name: "Eternity", family: "dragon", cost: 12 },
	66: { id: 66, name: "Gust", family: "dragon", cost: 8 },
	67: { id: 67, name: "Marina", family: "dragon", cost: 7 },
	68: { id: 68, name: "Scorch", family: "dragon", cost: 9 },
	69: { id: 69, name: "Tidal", family: "dragon", cost: 5 },
	70: { id: 70, name: "Willow", family: "dragon", cost: 10 },
};
